config/routes.rb
Tanks::Application.routes.draw do

  devise_for :users

  resources :clones, :tiroirs, :users

  root :to => 'pages#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  has_many :positionings, dependent: :destroy
  has_many :positions, 	  through: :positionings
  has_many :users,		  	through: :positionings

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
end
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  admin                  :boolean
#

app/controllers/users_controller.rb
# encoding: UTF-8
	class UsersController < ApplicationController

	before_filter :signed_in?
	before_filter :admin_user, only: [:index,:edit,:new]

	def new
		@user = User.new
		@users = User.all
	end	

	def create
		@user = User.new params[:user]
		unless @user.save
			redirect_to new_user_path, flash: {error: error_messages(@user)}
		else
			redirect_to users_path, flash: {success: "L'utilisateur a bien été crée"}
		end	
	end

	def edit
		@user = User.find(params[:id])
		@users = User.all
	end

	def update
		@user = User.find(params[:id])
		unless @user.update_attributes params[:user]
			flash[:error] = error_messages @user
			render :edit, id: @user
		else
			redirect_to users_path, flash: {success: "L'utilisateur a bien été mis à jour !"}
		end
	end

	def destroy
		User.find(params[:id]).destroy
		redirect_to users_path, flash: {success: "L'utilisateur a bien été supprimé !"}
	end	
	
	def index
		@users = User.all
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list_users.haml
%table.table.table-bordered
	%thead
		%th Email
		%th	Admin
		%th
	%tr
		%td{colspan:3, style: 'text-align:center'}
			%strong= link_to 'Ajouter un utilisateur', new_user_path
	- users.each do |user|
		%tr
			%td= user.email
			%td= "Oui" if user.admin
			%td
				= link_to "<div class='icon-pencil'></div>".html_safe, edit_user_path(user), 	title: "Modifier"
				= link_to "<div class='icon-remove'></div>".html_safe, user, method: :delete, title: 'Supprimer', confirm: "Supprimer cet utilisateur ?"

app/views/users/edit.haml
.row
	.span5.offset1
		=render 'list_users', users: @users
	.span5
		=form_for @user do |f|
			.well
				%table
					%tr
						%td
							%strong Email* : 
						%td
							=f.text_field :email
					%tr
						%td
							%strong Admin* :
						%td
							Oui
							=f.radio_button :admin, 't'
							Non
							=f.radio_button :admin, 'f'
				%br/
				=f.submit 'Valider', class: 'btn-primary'

app/views/users/index.haml
.row
	.span4.offset1
		= render 'list_users', users: @users

app/views/users/new.haml
.row
	.span5.offset1
		=render 'list_users', users: @users
	.span5
		=form_for @user do |f|
			.well
				%table
					%tr
						%td
							%strong Email* : 
						%td
							=f.text_field :email
					%tr
						%td
							%strong Admin* :
						%td
							Oui
							=f.radio_button :admin, 't'
							Non
							=f.radio_button :admin, 'f'
					%tr
						%td
							%strong Mot de passe* :
						%td
							=f.password_field :password
					%tr
						%td
							%strong Confirmation mot de passe* :
						%td		
							=f.password_field :password_confirmation
				%br/
				=f.submit 'Valider', class: 'btn-primary'