config/routes.rb
Tanks::Application.routes.draw do

  devise_for :users

  resources :clones, :tiroirs, :users

  root :to => 'pages#index'
end

app/views/shared/_admin_links.haml
.row
	.span2.well.menu
		%h6.pull-right Menu administrateur
		%br/
		%br/
		- if current_user.admin
			%strong.pull-right= link_to 'Gestion utilisateurs', users_path
		%strong.pull-right= link_to 'Ajouter un clone', new_clone_path 
		%br/
		%br/
		.small.pull-right= link_to 'Se déconnecter', destroy_user_session_path, method: :delete

app/views/shared/_search_filters.haml
.row#filters{ :style => 'font-size: 10pt;display:none' }
	.span9.offset1
		Type I :
		%select.span1
			%option Tous
			%option HEK
			%option COS-1
			%option IC6
			%option CHO
			%option	Véro
			%option SF21
			%option SF9
			%option Hi-5
		Type II : 
		%select.span2
			%option Tous
			%option Lignées adhérente
			%option Lignées en suspension
		Client : 
		%select.span2
			%option Tous
			%option Lignées de base
			%option Biomérieux
			%option Necker
			%option Netris Pharma
			%option Sisène
			%option Sastim
		Site :
		%select.span2
			%option Tous
			%option Grenoble
			%option Lyon
		%a{ :href => '#', :style => 'margin-left:15px;', :onclick => "$('#filters').hide('fast')" }
			%i.icon-remove

app/views/shared/_search_form.haml
.span8.offset1.lead
	Recherche
	%h5.pull-right= link_to 'Critères avancés', '#', { :style => 'margin-right:90px', id: 'link_filters' }
	%form.form-horizontal
		.input-append
			%input#search.input-xxlarge{ :placeholder => 'Saisissez votre recherche' }
				%button#search_button.btn.btn-large.btn-info{ :style => 'margin-left:-6px;'}
					%i.icon-search
= render 'shared/search_filters'