config/routes.rb
Tanks::Application.routes.draw do

  devise_for :users

  resources :clones, :tiroirs, :users

  root :to => 'pages#index'
end

app/models/clone.rb
# encoding: UTF-8
class Clone < ActiveRecord::Base

	attr_accessible :typeI, :typeII, :nom, :reference, :origine, :localisation, :client, :client_attributes, :date_banking, :milieu_congelation, :tests

	belongs_to :client

	has_many  :positionings, 	 	dependent: :destroy
	has_many  :users,		 	 		 	through: :positionings

	validates :typeI,  			 	 	length: { maximum: 50 },  					presence: true
	validates :typeII, 			   	length: { maximum: 50 },  					presence: true
	validates :nom,				 		 	length: { maximum: 100 }, 					presence: true
	validates :localisation, 		inclusion: { in: %w(Lyon Grenoble), presence: true, message: "%{value} n'est pas une valeur correcte (Lyon ou Grenoble)" } 
	validates :reference,		 		length: { maximum: 100 }
	validates :origine,			 		length: { maximum: 100 }
	validates_datetime :date_banking,																presence: true

	accepts_nested_attributes_for :client, :reject_if => lambda { |attr| attr['nom'].empty? }

	def first_position
		positionings.first.position
	end

	def last_position
		positionings.last.position
	end

	def tiroir
		boite.tiroir
	end

	def boite
		first_position.boite
	end

	def positions_in_table
		positionings.count == 1 ? "#{tiroir.numero}/#{boite.numero}/#{first_position.numero}" : "#{tiroir.numero}/#{boite.numero}/#{first_position.numero} à #{last_position.numero}"
	end

	def client_in_table
		client.nil? ? 'Lignée de base' : client.nom
	end
end
# == Schema Information
#
# Table name: clones
#
#  id                 :integer         not null, primary key
#  typeI              :string(255)
#  typeII             :string(255)
#  client_id          :integer
#  nom                :string(255)
#  reference          :string(255)
#  origine            :string(255)
#  localisation       :string(255)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  date_banking       :datetime
#  milieu_congelation :string(255)
#  tests              :string(255)
#

app/controllers/clones_controller.rb
# encoding: UTF-8
class ClonesController < ApplicationController

	before_filter :authenticate_user!

	def new
		@clone = Clone.new
		@clone.client = Client.new
	end

	def create
		@clone = Clone.new params[:clone]
		unless @clone.save
			redirect_to new_clone_path, flash: { error: error_messages(@clone) }
		else
			create_positioning
			redirect_to root_path, flash: { success: "Le clone a bien été crée !"}
		end	
	end

	def show
		@clone = Clone.find(params[:id])
		@tiroir = @clone.tiroir
		@boites = @tiroir.boites.order(:numero)
	end

	def edit
		@clone = Clone.find(params[:id])
	end	

	def update
		@clone = Clone.find(params[:id])
		unless @clone.update_attributes params[:clone]
			flash[:error] = error_messages @clone
			render :edit, id: @clone
		else
			@clone.positionings.destroy_all
			create_positioning
			redirect_to clone_path(@clone), flash: { success: "Le clone a bien été mis à jour !"}
		end
	end

	def destroy
		Clone.find(params[:id]).destroy
		redirect_to tiroirs_path, flash: { success: "Le clone a bien été supprimé !" }
	end

	private
		def create_positioning
			tiroir = Tiroir.where(site: params[:clone][:localisation], numero: params[:tiroir]).first
			boite = Boite.where(tiroir_id: tiroir, numero: params[:boite]).first
			(params[:first_position]..params[:last_position]).each do |numero|
				position = Position.where(boite_id: boite, numero: numero).first
				Positioning.create!(user: current_user, clone: @clone, position_ref: position)
			end
		end
end

app/helpers/clones_helper.rb
module ClonesHelper
end

app/views/clones/_fields_client.haml
= f.text_field :nom

app/views/clones/edit.haml
.row
	.span6.offset1.well
		%h6 CREATION CLONE
		%br/
		= form_for @clone do |f|
			%table
				%tr
					%td
						%strong Type 1
					%td
						= f.select :typeI, %w(HEK CHO COS-1 COS-7 IC6 Véro BHK21 MDCK T3/Duck RK13 NSO SF21 SF9 Hi-5 Hybridome Sp2O/Ag14 MRC5 CHO-DG44 CHO-S HEK-FS HEK-Ebna 293T HEK-293 HEK-2sus HEK-3F6), {}, class: 'span2'
				%tr
					%td	
						%strong Type 2
					%td
						= f.select :typeII, [ ["Lignée en suspension", "suspension"], ["Lignée adhérente", "adhérente"] ], {}, class: 'span3'
				%tr
					%td
						%strong Client (si lignée cliente)
					%td
						= f.fields_for(:client) {|client_builder| render 'fields_client', f: client_builder}
				%tr
					%td
						%strong Nom
					%td
						= f.text_field :nom
				%tr
					%td
						%strong Date de banking
					%td
						= f.date_select :date_banking, {prompt: {day: 'Jour', month: 'Mois', year: 'Année'}, use_month_numbers: true, order: [:day,:month,:year]}, {class: 'date_select'}
				%tr
					%td	
						%strong Référence
					%td
						= f.text_field :reference
				%tr
					%td
						%strong Localisation
					%td
						= f.select :localisation, %w(Grenoble Lyon), {}, class: 'span2'
				%tr
					%td
						%strong	Position
				%tr
					%td
						%dd Rack
					%td
						%select{ name: 'tiroir', class: 'input-small' }= options_for_select((1..6), @clone.tiroir.numero)
				%tr
					%td
						%dd Boite
					%td
						%select{ name: 'boite', class: 'input-small' }= options_for_select((1..5), @clone.boite.numero)		
				%tr
					%td
						%dd Numéro
					%td
						%select{ name: 'first_position', class: 'input-small' }= options_for_select((1..25), @clone.first_position.numero)	
						à
						%select{ name: 'last_position', class: 'input-small' }= options_for_select((1..25), @clone.last_position.numero)
				%tr
					%td
						%strong Origine
					%td
						= f.text_field :origine
				%tr
					%td
						%strong Milieu de congélation
					%td
						= f.text_field :milieu_congelation
				%tr
					%td
						%strong Tests
					%td
						= f.text_field :tests
			=f.submit 'Valider', class: "btn-primary btn-gigantic"
		%span.pull-right
			= link_to "Retour à l'accueil", url_for(:back)

app/views/clones/new.haml
.row
	.span6.offset1.well
		%h6 CREATION CLONE
		%br/
		= form_for @clone do |f|
			%table
				%tr
					%td
						%strong Type 1
					%td
						= f.select :typeI, %w(HEK CHO COS-1 COS-7 IC6 Véro BHK21 MDCK T3/Duck RK13 NSO SF21 SF9 Hi-5 Hybridome Sp2O/Ag14 MRC5 CHO-DG44 CHO-S HEK-FS HEK-Ebna 293T HEK-293 HEK-2sus HEK-3F6), {}, class: 'span2'
				%tr
					%td	
						%strong Type 2
					%td
						= f.select :typeII, [ ["Lignée en suspension", "suspension"], ["Lignée adhérente", "adhérente"] ], {}, class: 'span3'
				%tr
					%td
						%strong Client (si lignée cliente)
					%td
						= f.fields_for(:client) {|client_builder| render 'fields_client', f: client_builder}
				%tr
					%td
						%strong Nom
					%td
						= f.text_field :nom
				%tr
					%td
						%strong Date de banking
					%td
						= f.date_select :date_banking, {prompt: {day: 'Jour', month: 'Mois', year: 'Année'}, use_month_numbers: true, order: [:day,:month,:year]}, {class: 'date_select'}
				%tr
					%td
						%strong Référence
					%td
						= f.text_field :reference
				%tr
					%td
						%strong Localisation
					%td
						= f.select :localisation, %w(Grenoble Lyon), {}, class: 'span2'
				%tr
					%td
						%strong	Position
				%tr
					%td
						%dd Rack
					%td
						%select{ name: 'tiroir', class: 'input-small' }= options_for_select (1..6)
				%tr
					%td
						%dd Boite
					%td
						%select{ name: 'boite',  class: 'input-small' }= options_for_select (1..5)
				%tr
					%td
						%dd Numéro
					%td
						%select{ name: 'first_position', class: 'input-small' }= options_for_select (1..25)
						à
						%select{ name: 'last_position',  class: 'input-small' }= options_for_select (1..25)
				%tr
					%td
						%strong Origine
					%td
						= f.text_field :origine
				%tr
					%td
						%strong Milieu de congélation
					%td
						= f.text_field :milieu_congelation
				%tr
					%td
						%strong Tests
					%td
						= f.text_field :tests
			=f.submit 'Valider', class: "btn-primary btn-gigantic"
		%span.pull-right
			= link_to "Retour à l'accueil", url_for(tiroirs_path)

app/views/clones/show.haml
.row
	.span10.offset1.well
		%h4= "Clone #{@clone.nom}"
		%br/
		%table
			%tr
				%td
					= "Type : #{@clone.typeI}"
					= "<br/>Référence : #{@clone.reference}".html_safe unless @clone.reference.blank?
					= "<br/>Position : #{@clone.positions_in_table} (#{@clone.localisation})".html_safe
				%td{style: 'padding-left:150px'}
					= "Client : #{@clone.client_in_table}<br/>".html_safe unless @clone.client.blank?
					= "Type : #{@clone.typeII}".html_safe
					= "<br/>Milieu de congélation : #{@clone.milieu_congelation}".html_safe unless @clone.milieu_congelation.blank?
					= "<br/>Tests : #{@clone.tests}".html_safe unless @clone.tests.blank?
		%br/
		= link_to "<div class='icon-pencil'> Modifier</div>".html_safe, edit_clone_path(@clone), 	title: "Modifier"
		= link_to "<div class='icon-remove'> Supprimer</div>".html_safe, @clone, method: :delete, title: 'Supprimer', confirm: "Supprimer ce clone ?"

= render 'tiroirs/show'